test_1a_register (__main__.GSChrome) ... ok
test_1b_login (__main__.GSChrome) ... ok
test_2a_mount_container (__main__.GSChrome) ... ok
test_2b_disconnect_container (__main__.GSChrome) ... ok
test_3_setting_up (__main__.GSChrome) ... Traceback (most recent call last):
  File "./source/GSchrome.py", line 86, in <module>
    unittest.main(verbosity=2)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 395, in __call__
    return self.run(*args, **kwds)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/source/data_test_preparation.py", line 241, in test_3_setting_up
    self.files()
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/source/data_test_preparation.py", line 183, in files
    self.upload_test_file(file_name, GST.local_file_paths["file_to_move_to_folder_source_path"], GST.gs_file_paths["file_to_move_to_folder_source_path"], "moving data")
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/source/data_test_preparation.py", line 126, in upload_test_file
    self.uploading(filename, gs_path, data)
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/source/genome_space_test.py", line 156, in uploading
    self.send_request(function, "upload_file()")
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/source/genome_space_test.py", line 73, in send_request
    driver.execute_script(function_call)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 403, in execute_script
    {'script': script, 'args':converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 349, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 380, in _request
    resp = self._conn.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
